import Header from '@/components/Header'
import './style/globals.css'
import { Inter } from 'next/font/google'
import Footer from '@/components/Footer'
import { Metadata } from 'next'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: {
    default: 'B2B Malaysia to Vietnam | Matrade'
  },
  description: 'Generated by create next app',
  icons: {
    icon: '/icons/favicon/favicon.png'
  },
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='max-w-[1920px] m-auto font-openSan'>
        <Header />
        <main>
          {children}
        </main>
        <Footer />
      </body>
    </html>
  )
}
